"""
Diagnostic helper routines for the GAREUS package.

This module collects a handful of utility functions that analyse
production data generated by umbrella sampling and GaMD runs.  The
functions defined here were originally part of the monolithic
``gareus_peptide.py`` script.  They have been relocated to enable
reuse by other modules and to simplify testing.  The helpers operate
purely on CSV/NumPy data residing on disk and do not depend on any
OpenMM constructs.

Available functions
-------------------

``compute_gamd_reweighting_diagnostics``
    Post\u2011run diagnostics for GaMD boost reweighting reliability.  This
    examines the boost magnitude trace stored in ``analysis_arrays.npz``
    and computes basic statistics and diagnostics such as the mean,
    standard deviation, anharmonicity and effective sample size (ESS)
    for cumulant reweighting.  A dictionary summarising the results
    and any warnings is returned.

``validate_us_mbar_inputs``
    Validate final-production umbrella\u2011sampling data before running
    PyMBAR/PMF analysis.  This checks that the umbrella bias matrix
    shape matches the number of windows and that sufficient samples
    exist in each window.  It also computes histogram overlaps
    between neighbouring windows to identify weakly connected regions.

``pmf_probability``, ``js_divergence_1d``, ``pmf_rmse_1d``, ``barrier_error_1d``
    PMF-vs-reference comparison metrics used by the epoch/frame-count
    convergence loops: normalising a raw PMF into a probability
    distribution, Jensen-Shannon divergence and RMSE/barrier-height
    error between two PMFs restricted to well-sampled bins.

The private helpers ``_read_csv_dicts``, ``_safe_float``,
``_sample_counts_by_window`` and ``_hist_overlap_np`` are exposed for
internal use but not exported by the package.
"""

from __future__ import annotations

from pathlib import Path
import csv
import math
import os
import json
from typing import List, Dict, Any, Optional

import numpy as np

__all__ = [
    "compute_gamd_reweighting_diagnostics",
    "validate_us_mbar_inputs",
    "pmf_probability",
    "js_divergence_1d",
    "pmf_rmse_1d",
    "barrier_error_1d",
]


def _read_csv_dicts(path: Path) -> list[dict]:
    """Return a list of dicts for each row in a CSV file."""
    path = Path(path)
    if not path.exists():
        return []
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def _safe_float(value: Any, default: float = float("nan")) -> float:
    """Convert ``value`` to ``float`` if possible, else return ``default``."""
    try:
        out = float(value)
    except Exception:
        return default
    return out if math.isfinite(out) else default


def _sample_counts_by_window(window_arr: np.ndarray, n_windows: int) -> list[int]:
    """Compute the number of samples falling into each umbrella window."""
    out = np.zeros(int(n_windows), dtype=np.int64)
    if window_arr.size:
        valid = window_arr[(window_arr >= 0) & (window_arr < int(n_windows))]
        if valid.size:
            out += np.bincount(valid.astype(np.int64), minlength=int(n_windows))[: int(n_windows)]
    return [int(x) for x in out]


def _hist_overlap_np(a: np.ndarray, b: np.ndarray, lo: float, hi: float, bins: int = 80) -> float:
    """Estimate the histogram overlap between two distributions."""
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    a = a[np.isfinite(a)]
    b = b[np.isfinite(b)]
    if a.size < 5 or b.size < 5:
        return float("nan")
    if not math.isfinite(lo) or not math.isfinite(hi) or hi <= lo:
        allv = np.concatenate([a, b])
        if allv.size < 2:
            return float("nan")
        lo, hi = float(np.min(allv)), float(np.max(allv))
    pad = max(0.1, 0.02 * (hi - lo))
    ha, _ = np.histogram(a, bins=max(8, int(bins)), range=(lo - pad, hi + pad))
    hb, _ = np.histogram(b, bins=max(8, int(bins)), range=(lo - pad, hi + pad))
    if ha.sum() <= 0 or hb.sum() <= 0:
        return float("nan")
    pa = ha.astype(float) / float(ha.sum())
    pb = hb.astype(float) / float(hb.sum())
    return float(np.minimum(pa, pb).sum())


def pmf_probability(pmf: dict) -> np.ndarray:
    """Normalize a raw PMF ``prob`` array to a finite, non-negative distribution."""
    prob = np.asarray(pmf.get('prob', []), dtype=np.float64)
    total = float(np.nansum(prob))
    if total > 0:
        prob = prob / total
    return np.where(np.isfinite(prob) & (prob >= 0), prob, 0.0)


def js_divergence_1d(P, Q) -> float:
    """Jensen-Shannon divergence (nats) between two (unnormalized) 1D distributions."""
    P = pmf_probability({'prob': P})
    Q = pmf_probability({'prob': Q})
    if P.size != Q.size:
        n = min(P.size, Q.size)
        P = P[:n]
        Q = Q[:n]
    M = 0.5 * (P + Q)
    with np.errstate(divide='ignore', invalid='ignore'):
        a = np.where(P > 0, P * np.log(P / np.maximum(M, 1e-300)), 0.0)
        b = np.where(Q > 0, Q * np.log(Q / np.maximum(M, 1e-300)), 0.0)
    return float(0.5 * (np.sum(a) + np.sum(b)))


def pmf_rmse_1d(F, Fref, P, Pref, min_prob=0.0) -> float:
    """RMSE between two PMFs, restricted to bins with probability above ``min_prob`` on both sides."""
    F = np.asarray(F, dtype=np.float64)
    Fref = np.asarray(Fref, dtype=np.float64)
    P = np.asarray(P, dtype=np.float64)
    Pref = np.asarray(Pref, dtype=np.float64)
    n = min(F.size, Fref.size, P.size, Pref.size)
    if n <= 0:
        return float('nan')
    F = F[:n]
    Fref = Fref[:n]
    P = P[:n]
    Pref = Pref[:n]
    mask = np.isfinite(F) & np.isfinite(Fref) & (P > float(min_prob)) & (Pref > float(min_prob))
    if not np.any(mask):
        return float('nan')
    d = F[mask] - Fref[mask]
    return float(np.sqrt(np.mean(d * d)))


def barrier_error_1d(F, Fref, P, Pref) -> float:
    """Absolute difference between two PMFs' maxima, restricted to bins with positive probability on both sides."""
    F = np.asarray(F, dtype=np.float64)
    Fref = np.asarray(Fref, dtype=np.float64)
    P = np.asarray(P, dtype=np.float64)
    Pref = np.asarray(Pref, dtype=np.float64)
    n = min(F.size, Fref.size, P.size, Pref.size)
    if n <= 0:
        return float('nan')
    mask = np.isfinite(F[:n]) & np.isfinite(Fref[:n]) & (P[:n] > 0) & (Pref[:n] > 0)
    if not np.any(mask):
        return float('nan')
    return float(abs(np.nanmax(F[:n][mask]) - np.nanmax(Fref[:n][mask])))


def compute_gamd_reweighting_diagnostics(out_dir: Path, temperature_k: float) -> dict:
    """Compute diagnostics assessing GaMD boost reweighting reliability.

    This function reads the GaMD boost array from ``analysis_arrays.npz``
    within ``out_dir`` and computes basic statistics including the
    mean, standard deviation, minima and maxima of the boost.  It
    calculates the anharmonicity (using the local ``boost_anharmonicity``
    function defined in the monolithic script) and the effective
    sample size (ESS) based on the exponential of the boost scaled by
    ``1/(k_B*T)``.  Warnings are added to the output if the number of
    finite values is small or the distribution exhibits anomalies.  If
    the array is missing or unreadable, an error status is returned.

    In addition to the pooled ESS, per-window ESS values are computed
    so that individual window reweighting quality can be assessed
    without the bimodal collapse that occurs when windows have very
    different mean boosts.  A ``calibration_range_warnings`` list
    identifies windows whose mean boost far exceeds the median (a sign
    that those windows sample PEs outside the [Vmin, Vmax] calibration
    range and that the boost saturates or vanishes there).

    Parameters
    ----------
    out_dir:
        Path to the run directory containing ``analysis_arrays.npz``.
    temperature_k:
        Simulation temperature in Kelvin.

    Returns
    -------
    dict
        A dictionary summarising the diagnostics and warnings.  See
        ``gareus_peptide.compute_gamd_reweighting_diagnostics`` for
        further context.

    New keys (F3, F2)
    -----------------
    per_window_ess : dict[int, dict]
        Mapping window_id -> {"ess": float, "ess_fraction": float, "n_frames": int}.
    ess_fraction_per_window_min : float
        Minimum per-window ESS fraction across all windows.
    ess_fraction_per_window_median : float
        Median per-window ESS fraction across all windows.
    calibration_range_warnings : list[str]
        One entry per window whose mean boost exceeds 3x the median of all
        windows\'  mean boosts, indicating calibration range mismatch.
    """
    out_dir = Path(out_dir)
    npz_path = out_dir / "analysis_arrays.npz"
    warnings: list[str] = []
    result: dict[str, Any] = {
        "status": "missing",
        "analysis_arrays_npz": str(npz_path),
        "warnings": warnings,
    }
    if not npz_path.exists():
        warnings.append("analysis_arrays.npz is missing; cannot compute GaMD boost diagnostics")
        return result
    try:
        with np.load(npz_path, allow_pickle=False) as data:
            boost_kj = np.asarray(data.get("gamd_boost_total_kj_mol", []), dtype=float)
            window_arr = np.asarray(data.get("window", []), dtype=np.int32)
    except Exception as exc:
        result["status"] = "error"
        warnings.append(f"could not read GaMD boost array: {exc}")
        return result
    finite = boost_kj[np.isfinite(boost_kj)]
    if finite.size == 0:
        result["status"] = "warning"
        warnings.append("no finite GaMD boost values were found in analysis_arrays.npz")
        return result
    boost_kcal = finite / 4.184
    # Defer to the implementation in gareus_peptide for anharmonicity
    try:
        from .logger import boost_anharmonicity
        an = boost_anharmonicity(boost_kcal.tolist())
    except Exception:
        an = {"score": float("nan")}
    # Effective sample size diagnostics based on exp(beta*boost)
    beta_1_over_kj = 1.0 / (0.00831446261815324 * float(temperature_k))
    logw = beta_1_over_kj * finite
    logw -= float(np.max(logw))
    weights = np.exp(logw)
    sw = float(np.sum(weights))
    sw2 = float(np.sum(weights * weights))
    ess = float(sw * sw / sw2) if sw2 > 0.0 else float("nan")
    ess_frac = float(ess / finite.size) if finite.size else float("nan")
    mean_kcal = float(np.mean(boost_kcal))
    sd_kcal = float(np.std(boost_kcal))
    # Per-window boost std -- detect individual high-variance windows
    per_window_sd: dict[int, float] = {}
    if window_arr.size == boost_kj.size and window_arr.size > 0:
        finite_mask = np.isfinite(boost_kj)
        for wi in np.unique(window_arr[finite_mask]):
            mask = finite_mask & (window_arr == wi)
            vals = boost_kj[mask] / 4.184
            if vals.size >= 2:
                per_window_sd[int(wi)] = float(np.std(vals))

    # F3: Per-window ESS -- avoids the bimodal collapse that occurs when
    # windows have very different mean boosts and the pooled distribution
    # is multimodal.  Uses the same beta and formula as the pooled ESS
    # but restricts each computation to frames from a single window.
    per_window_ess: dict[int, dict] = {}
    ess_fracs_per_window: list[float] = []
    if window_arr.size == boost_kj.size and window_arr.size > 0:
        finite_mask_ess = np.isfinite(boost_kj)
        for wi in np.unique(window_arr[finite_mask_ess]):
            mask_w = finite_mask_ess & (window_arr == wi)
            vals_w = boost_kj[mask_w]
            n_w = int(vals_w.size)
            if n_w < 2:
                continue
            logw_w = beta_1_over_kj * vals_w
            logw_w = logw_w - float(np.max(logw_w))
            w_w = np.exp(logw_w)
            sw_w = float(np.sum(w_w))
            sw2_w = float(np.sum(w_w * w_w))
            ess_w = float(sw_w * sw_w / sw2_w) if sw2_w > 0.0 else float("nan")
            ess_frac_w = float(ess_w / n_w) if (n_w > 0 and math.isfinite(ess_w)) else float("nan")
            per_window_ess[int(wi)] = {
                "ess": ess_w,
                "ess_fraction": ess_frac_w,
                "n_frames": n_w,
            }
            if math.isfinite(ess_frac_w):
                ess_fracs_per_window.append(ess_frac_w)
    ess_frac_pw_min = float(np.min(ess_fracs_per_window)) if ess_fracs_per_window else float("nan")
    ess_frac_pw_median = float(np.median(ess_fracs_per_window)) if ess_fracs_per_window else float("nan")

    # F2: Calibration range warnings -- detect windows whose mean boost
    # (in kJ/mol) is far above the median.  These windows likely sample
    # PEs outside the [Vmin, Vmax] range frozen from the k=0 calibration
    # run, causing the boost to saturate or vanish and corrupting
    # reweighting for those windows.
    calibration_range_warnings: list[str] = []
    if window_arr.size == boost_kj.size and window_arr.size > 0:
        finite_mask_cr = np.isfinite(boost_kj)
        window_mean_boosts_kj: dict[int, float] = {}
        for wi in np.unique(window_arr[finite_mask_cr]):
            mask_w = finite_mask_cr & (window_arr == wi)
            vals_w = boost_kj[mask_w]
            if vals_w.size >= 1:
                window_mean_boosts_kj[int(wi)] = float(np.mean(vals_w))
        if len(window_mean_boosts_kj) >= 2:
            all_means = list(window_mean_boosts_kj.values())
            median_mean_kj = float(np.median(all_means))
            if median_mean_kj > 0.0:
                threshold_kj = 3.0 * median_mean_kj
                for wi, mean_b in sorted(window_mean_boosts_kj.items()):
                    if mean_b > threshold_kj:
                        calibration_range_warnings.append(
                            f"window {wi}: mean boost {mean_b:.1f} kJ/mol exceeds 3\u00d7 median ({median_mean_kj:.1f} kJ/mol)"
                        )

    result.update({
        "status": "ok",
        "n_finite": int(finite.size),
        "n_total": int(boost_kj.size),
        "boost_mean_kcal_mol": mean_kcal,
        "boost_sd_kcal_mol": sd_kcal,
        "boost_min_kcal_mol": float(np.min(boost_kcal)),
        "boost_max_kcal_mol": float(np.max(boost_kcal)),
        "anharmonicity": an,
        "reweighting_ess": ess,
        "reweighting_ess_fraction": ess_frac,
        "beta_1_over_kj_mol": float(beta_1_over_kj),
        "reweighting_note": "ESS uses exp(beta*boost) as a diagnostic of weight degeneracy; final GaMD PMF details may use cumulant expansion or MBAR-specific treatment.",
        "per_window_boost_sd_kcal_mol": per_window_sd,
        "per_window_ess": per_window_ess,
        "ess_fraction_per_window_min": ess_frac_pw_min,
        "ess_fraction_per_window_median": ess_frac_pw_median,
        "calibration_range_warnings": calibration_range_warnings,
    })
    # Add warnings based on heuristics from the monolith
    if finite.size < 100:
        warnings.append("fewer than 100 finite boost samples; GaMD boost diagnostics are noisy")
    if math.isfinite(sd_kcal) and sd_kcal > 6.0:
        warnings.append(f"boost standard deviation is {sd_kcal:.2f} kcal/mol (>~6); cumulant reweighting may be unreliable")
    hot_windows = sorted(wi for wi, sd in per_window_sd.items() if sd > 2.0)
    if hot_windows:
        hot_str = ", ".join(str(w) for w in hot_windows[:10])
        if len(hot_windows) > 10:
            hot_str += f" ... ({len(hot_windows)} total)"
        warnings.append(
            f"windows [{hot_str}] have GaMD boost \u03c3 > 2.0 kcal/mol; "
            f"high boost variance in these windows may corrupt MBAR/cumulant contributions"
        )
    try:
        score = float(an.get("score", float("nan")))
    except Exception:
        score = float("nan")
    if math.isfinite(score) and score >= 1.0:
        warnings.append(f"boost anharmonicity score is {score:.2f}; non-Gaussian boost distribution")
    if math.isfinite(ess_frac) and ess_frac < 0.10:
        warnings.append(f"GaMD reweighting ESS fraction is {ess_frac:.3f}; weights are strongly degenerate")
    if sd_kcal <= 1.0e-8:
        warnings.append("GaMD boost trace is essentially constant; verify boost reading and GaMD production stage")
    if calibration_range_warnings:
        for crw in calibration_range_warnings:
            warnings.append(f"calibration range: {crw}")
    if warnings:
        result["status"] = "warning"
    return result


def validate_us_mbar_inputs(out_dir: Path, temperature_k: float, target_overlap: float = 0.30) -> dict:
    """Validate umbrella\u2011sampling inputs for MBAR/PMF analysis.

    Checks umbrella windows and analysis arrays for consistent shapes,
    finite values and sufficient sample counts.  Computes histogram
    overlaps between neighbouring windows and reports any pairs below
    ``target_overlap``.  Returns a dictionary containing the status
    ("ok", "warning" or "error"), lists of warnings and errors, and
    summary statistics needed for downstream analysis.

    Parameters
    ----------
    out_dir:
        Directory containing ``umbrella_windows.csv`` and ``analysis_arrays.npz``.
    temperature_k:
        Temperature of the simulation in Kelvin (unused but kept for
        compatibility with the original signature).
    target_overlap:
        Threshold below which neighbouring window histogram overlap is
        considered weak.

    Returns
    -------
    dict
        A dictionary with keys documenting the validation outcome.  If
        ``errors`` is non\u2011empty, the status will be "error" and
        downstream MBAR/PMF analysis should not proceed.
    """
    out_dir = Path(out_dir)
    warnings: list[str] = []
    errors: list[str] = []
    windows_path = out_dir / "umbrella_windows.csv"
    explicit_windows_path = out_dir / "umbrella_explicit_windows.csv"
    graph_path = out_dir / "explicit_2d_neighbor_graph.csv"
    npz_path = out_dir / "analysis_arrays.npz"
    windows = _read_csv_dicts(windows_path)
    n_windows = len(windows)
    result: dict[str, Any] = {
        "status": "ok",
        "umbrella_windows_csv": str(windows_path),
        "analysis_arrays_npz": str(npz_path),
        "n_windows_from_csv": int(n_windows),
        "warnings": warnings,
        "errors": errors,
    }
    # Basic file existence checks
    if n_windows <= 0:
        errors.append("umbrella_windows.csv missing or empty")
    if not npz_path.exists():
        errors.append("analysis_arrays.npz missing")
    if errors:
        result["status"] = "error"
        return result

    # Sparse-2D detection mirrors gareus.analysis.validate_analysis_metadata_readiness:
    # the legacy umbrella_windows.csv table never carries explicit_2d/rectangular_grid
    # flags, so prefer umbrella_explicit_windows.csv (when present) for detection.
    # Windows are stored in a flat list; on sparse 2D grids flat index i/i+1 is
    # NOT a meaningful CV-space neighbor relation, so flat-adjacency overlap must
    # not be used there (see explicit_2d_neighbor_graph.csv edges instead).
    detect_rows = _read_csv_dicts(explicit_windows_path) or windows
    explicit_2d = any(str(r.get("explicit_2d", "0")) in {"1", "True", "true"} for r in detect_rows)
    rectangular = all(str(r.get("rectangular_grid", "0")) in {"1", "True", "true"} for r in detect_rows) if explicit_2d and detect_rows else False
    sparse_2d = bool(explicit_2d and not rectangular)
    result["explicit_2d"] = bool(explicit_2d)
    result["rectangular_grid"] = bool(rectangular)
    result["sparse_2d"] = bool(sparse_2d)

    # Load arrays and ensure required keys are present
    try:
        with np.load(npz_path, allow_pickle=False) as data:
            keys = set(data.files)
            required = {"cv_A", "window", "umbrella_reduced_bias_nk"}
            missing = sorted(required - keys)
            if missing:
                errors.append("analysis_arrays.npz missing required arrays: " + ", ".join(missing))
                result["status"] = "error"
                return result
            cv = np.asarray(data["cv_A"], dtype=float)
            win = np.asarray(data["window"], dtype=np.int64)
            ub = np.asarray(data["umbrella_reduced_bias_nk"], dtype=float)
            potential = np.asarray(data.get("potential_kj_mol", []), dtype=float)
    except Exception as exc:
        result["status"] = "error"
        errors.append(f"could not read analysis_arrays.npz: {exc}")
        return result
    n_samples = int(cv.size)
    result["n_samples"] = n_samples
    result["bias_shape"] = list(ub.shape)
    # Shape sanity checks
    if n_samples <= 0:
        errors.append("no samples in analysis_arrays.npz")
    if ub.ndim != 2:
        errors.append(f"umbrella_reduced_bias_nk must be 2D, got shape {ub.shape}")
    elif ub.shape[0] != n_samples:
        errors.append(f"umbrella bias matrix first dimension {ub.shape[0]} does not match n_samples {n_samples}")
    elif ub.shape[1] != n_windows:
        errors.append(f"umbrella bias matrix has {ub.shape[1]} windows but umbrella_windows.csv has {n_windows}")
    if win.size != n_samples:
        errors.append("window array length does not match cv_A length")
    # Finite value checks
    if not np.all(np.isfinite(cv)):
        warnings.append("cv_A contains non-finite values")
    if ub.ndim == 2 and not np.all(np.isfinite(ub)):
        warnings.append("umbrella_reduced_bias_nk contains non-finite values")
    if potential.size and not np.all(np.isfinite(potential)):
        warnings.append("potential_kj_mol contains non-finite values")
    # Sample counts per window
    counts = _sample_counts_by_window(win, n_windows)
    result["sample_counts_by_window"] = counts
    zero = [i for i, c in enumerate(counts) if c <= 0]
    low = [i for i, c in enumerate(counts) if 0 < c < 10]
    if zero:
        errors.append("windows with zero production samples: " + ", ".join(map(str, zero)))
    if low:
        warnings.append("windows with fewer than 10 production samples: " + ", ".join(map(str, low)))
    # Neighbour histogram overlaps.
    centers = [_safe_float(r.get("center_A")) for r in windows]
    pair_rows: list[dict[str, Any]] = []
    connected = True
    if sparse_2d:
        # Sparse explicit 2D: flattened window order is not a neighbor relation.
        # Only compare windows that the neighbor GRAPH says are adjacent.
        result["neighbor_overlap_mode"] = "graph_edges_only; flattened window-order overlap intentionally skipped"
        if n_windows >= 2 and n_samples > 0:
            graph_rows = _read_csv_dicts(graph_path)
            if not graph_rows:
                warnings.append("sparse explicit 2D run has no explicit_2d_neighbor_graph.csv; skipping neighbor overlap connectivity check")
            else:
                finite_centers = [c for c in centers if math.isfinite(c)]
                lo = min(finite_centers) if finite_centers else float(np.nanmin(cv))
                hi = max(finite_centers) if finite_centers else float(np.nanmax(cv))
                for row in graph_rows:
                    wi = int(_safe_float(row.get("window_i"), -1))
                    wj = int(_safe_float(row.get("window_j"), -1))
                    if not (0 <= wi < n_windows and 0 <= wj < n_windows):
                        continue
                    a = cv[win == wi]
                    b = cv[win == wj]
                    ov = _hist_overlap_np(a, b, lo, hi, bins=80)
                    pair_rows.append({
                        "left_window": wi, "right_window": wj,
                        "edge_type": str(row.get("edge_type", "")),
                        "overlap": ov, "left_count": int(a.size), "right_count": int(b.size),
                    })
                # No flat-adjacency "disconnected" verdict on sparse 2D: soften to a
                # weak-overlap warning below rather than a false disconnection error.
    else:
        # 1D/rectangular fallback: flat i, i+1 is a meaningful CV-space neighbor.
        result["neighbor_overlap_mode"] = "flat adjacent windows for 1D/rectangular fallback"
        if n_windows >= 2 and n_samples > 0:
            finite_centers = [c for c in centers if math.isfinite(c)]
            lo = min(finite_centers) if finite_centers else float(np.nanmin(cv))
            hi = max(finite_centers) if finite_centers else float(np.nanmax(cv))
            for i in range(n_windows - 1):
                a = cv[win == i]
                b = cv[win == i + 1]
                ov = _hist_overlap_np(a, b, lo, hi, bins=80)
                pair_rows.append({"left_window": i, "right_window": i + 1, "overlap": ov, "left_count": int(a.size), "right_count": int(b.size)})
                if (not math.isfinite(ov)) or ov < 0.03:
                    connected = False
    result["neighbor_overlaps"] = pair_rows
    result["overlap_connected_at_0p03"] = bool(connected)
    weak = [r for r in pair_rows if math.isfinite(float(r["overlap"])) and float(r["overlap"]) < float(target_overlap)]
    result["neighbor_pairs_below_target_overlap"] = weak
    if pair_rows and not sparse_2d and not connected:
        errors.append("neighbor CV histogram overlap graph appears disconnected at threshold 0.03")
    if weak:
        warnings.append(f"{len(weak)} neighbor pair(s) below target overlap {target_overlap:.2f}")
    if errors:
        result["status"] = "error"
    elif warnings:
        result["status"] = "warning"
    else:
        result["status"] = "ok"
    return result
